### ISSUE TITLE
OnPositionChangedListener

### ISSUE THREAD

**Issue by omkar-tenkale** [hyuwah/DraggableView#3]
Im using
        **DraggableUtils.makeDraggable(ivLeft, Draggable.STICKY.NONE, true);**

and i need to show getX() and getY() in a textviw when position changed.

I'm trying to make two imageviews draggable inside a constraint layout
I tried 2 approaches but both failed.

**Approach 1**
```
  activityRootView.getViewTreeObserver().addOnGlobalLayoutListener(
                new ViewTreeObserver.OnGlobalLayoutListener() {

                    @SuppressLint("NewApi")
                    @Override
                    public void onGlobalLayout() {
                        //never gets called except on activity created
                        x = ivLeft.getX() 
                        y = ivLeft.getY() 
                      
                    }
                });
```

**Approach 2**
```

 ivLeft.setOnDragListener(new View.OnDragListener() {
            @Override
            public boolean onDrag(View v, DragEvent event) {
                        //never gets called
                        x = event.getX() 
                        y = event.getY() 
                return false;
            }
        });
```

**Comment by hyuwah** [comment]
Hi @omkar-tenkale, i [updated](https://github.com/hyuwah/DraggableView/releases/tag/0.4.0) the library to include an interface for listening to view update 
Because of this library is just wrapping around `setOnTouchListener`, the only way to get the updated view object is by implementing a listener interface.. 

Please take a look at the updated README for the usage, or feel free to reply to this if there are any questions
